In [1]:
import torch
import matplotlib.pyplot as plt
import numpy as np

num_example = 1000
true_w = torch.tensor([2, -3.4]).reshape(2, 1)
true_b = torch.tensor([2])
feature = torch.normal(0, 1, size=(num_example, 2))


def f(n, true_w, true_b):
    y = torch.matmul(n, true_w) + true_b
    e = torch.normal(0, 0.01,y.shape)
    y += e
    return y


label = f(feature, true_w, true_b)
# feature, label
# plt.figure(figsize=(12,8),dpi=80)
# plt.scatter(feature[:, 1], label)
# plt.show()

w = torch.normal(0, 1, size=(2, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
lr = 0.9
def net(x, w, b):
    return torch.matmul(x, w) + b

def loss(y_pre, y) :
    return ((y_pre - y)**2)/2

def sgd(w, b, lr):
    with torch.no_grad():
        w -= lr*w.grad/num_example
        b -= lr*b.grad/num_example
        # print(w.grad, b.grad)
        # print("----------------------------------------------")
        w.grad.zero_()
        b.grad.zero_()

# l = loss(net(feature, w, b), label)
# l.sum().backward()
# w.grad, b.grad

for num in range(7):
    l = loss(net(feature, w, b), label)
    l.sum().backward()
    # print(l, w.grad, b.grad)
    sgd(w, b, lr)
    # print(w.reshape(true_w.shape) - true_w, b - true_b)
    print(w, b)
    print("------------------------------------------------")


tensor([[ 1.8671],
        [-3.5780]], requires_grad=True) tensor([2.0765], requires_grad=True)
------------------------------------------------
tensor([[ 1.9845],
        [-3.3949]], requires_grad=True) tensor([2.0026], requires_grad=True)
------------------------------------------------
tensor([[ 1.9984],
        [-3.4001]], requires_grad=True) tensor([2.0010], requires_grad=True)
------------------------------------------------
tensor([[ 1.9996],
        [-3.4000]], requires_grad=True) tensor([2.0003], requires_grad=True)
------------------------------------------------
tensor([[ 1.9998],
        [-3.4000]], requires_grad=True) tensor([2.0001], requires_grad=True)
------------------------------------------------
tensor([[ 1.9998],
        [-3.4000]], requires_grad=True) tensor([2.0001], requires_grad=True)
------------------------------------------------
tensor([[ 1.9998],
        [-3.4000]], requires_grad=True) tensor([2.0001], requires_grad=True)
----------------------------------